version: "3"
services:
  basenode:
    build:
      context: ./BaseNode
      dockerfile: Dockerfile
    image: hadoopbasenode:0.1-ra
  masternode:
    image: hadoopbasenode:0.1-ra
    depends_on:
      - basenode
    ports:
      - "8020:8020"
      - "50070:50070"
      - "50090:50090"
      - "8032:8032"
      - "8030:8030"
      - "8088:8088"
      - "8031:8031"
      - "8033:8033"
    volumes:
      - ./volumes/masternode/nn:/nn
      - ./volumes/masternode/snn:/snn
    command: start_master.sh
    container_name: masternode
  workernode1:
    image: hadoopbasenode:0.1-ra
    depends_on:
      - masternode
    ports:
      - "50075:50075"
      - "50010:50010"
      - "50020:50020"
      - "8042:8042"
    volumes:
      - ./volumes/workernode1/dn:/dn
      - ./volumes/workernode1/yarn:/yarn
    command: start_worker.sh
    container_name: workernode1
  workernode2:
    image: hadoopbasenode:0.1-ra
    depends_on:
      - masternode
    ports:
      - "50076:50075"
      - "50011:50010"
      - "50021:50020"
      - "8043:8042"
    volumes:
      - ./volumes/workernode2/dn:/dn
      - ./volumes/workernode2/yarn:/yarn
    command: start_worker.sh
    container_name: workernode2
  workernode3:
    image: hadoopbasenode:0.1-ra
    depends_on:
      - masternode
    ports:
      - "50077:50075"
      - "50012:50010"
      - "50022:50020"
      - "8044:8042"
    volumes:
      - ./volumes/workernode3/dn:/dn
      - ./volumes/workernode3/yarn:/yarn
    command: start_worker.sh
    container_name: workernode3
  hadoopclient:
    build:
      context: ./ClientNode
      dockerfile: Dockerfile
    image: hadoopclientnode:0.1-ra
    depends_on:
      - masternode
    volumes:
      - ./volumes/shared:/shared
    command: /sbin/init
    container_name: hadoopclient
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./volumes/dbstore:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    container_name: mysqldb
  sparknode:
    build:
      context: ./SparkNode
      dockerfile: Dockerfile
    image: sparkclientnode:0.1-ra
    depends_on:
      - hadoopclient
      - mysqldb
    volumes:
      - ./volumes/shared:/shared
    command: /sbin/init
    container_name: sparknode
